######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 5 13:21:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += midicomp.h midifile.h t2mf.h
SOURCES += midicomp.c t2mflex.c yyread.c
